#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1.1_AR75516 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Sat Jul 24 10:57:16 AEST 2021
# SW Build 2960000 on Wed Aug  5 22:57:21 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xvlog --incr --relax -prj first_system2_tb_vlog.prj"
xvlog --incr --relax -prj first_system2_tb_vlog.prj 2>&1 | tee compile.log

echo "xvhdl --incr --relax -prj first_system2_tb_vhdl.prj"
xvhdl --incr --relax -prj first_system2_tb_vhdl.prj 2>&1 | tee -a compile.log

