#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1.1_AR75516 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Jul 24 10:57:18 AEST 2021
# SW Build 2960000 on Wed Aug  5 22:57:21 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 28655bacbf294e6aa0c8938f2b7efc07 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot first_system2_tb_behav xil_defaultlib.first_system2_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto 28655bacbf294e6aa0c8938f2b7efc07 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot first_system2_tb_behav xil_defaultlib.first_system2_tb xil_defaultlib.glbl -log elaborate.log

