#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1.1_AR75516 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Jul 24 10:57:25 AEST 2021
# SW Build 2960000 on Wed Aug  5 22:57:21 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim first_system2_tb_behav -key {Behavioral:sim_1:Functional:first_system2_tb} -tclbatch first_system2_tb.tcl -log simulate.log"
xsim first_system2_tb_behav -key {Behavioral:sim_1:Functional:first_system2_tb} -tclbatch first_system2_tb.tcl -log simulate.log

